CREATE TABLE TBL_ORGANIZATION (
    ORGANIZATION_ID INT NOT NULL AUTO_INCREMENT,
    ORGANIZATION_NAME VARCHAR(255),
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ORGANIZATION_ID)
);

CREATE TABLE TBL_CUSTOMER (
    CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
    ORGANIZATION_ID INT NOT NULL,
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID),
    INDEX IDX_ORGANIZATION_ID (ORGANIZATION_ID)
);

CREATE TABLE TBL_FIELD (
    FIELD_ID INT NOT NULL AUTO_INCREMENT,
    FIELD_NAME VARCHAR(255),
    FIELD_VARIANT VARCHAR(50),
    FIELD_PARAMS VARCHAR(255),
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (FIELD_ID)
);

CREATE TABLE TBL_DEFAULT_FIELD (
    FIELD_ID INT NOT NULL,
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (FIELD_ID)
);

CREATE TABLE TBL_ORGANIZATION_FIELD (
    ORGANIZATION_ID INT NOT NULL,
    FIELD_ID INT NOT NULL,
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ORGANIZATION_ID, FIELD_ID)
);

CREATE TABLE TBL_FIELD_VALUE (
    FIELD_VALUE_ID INT NOT NULL AUTO_INCREMENT,
    FIELD_VALUE_VARCHAR VARCHAR(255),
    FIELD_VALUE_TEXT TEXT,
    FIELD_VALUE_NUMBER INT,
    FIELD_VALUE_DATETIME DATETIME,
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (FIELD_VALUE_ID),
    INDEX IDX_FIELD_VALUE_VARCHAR (FIELD_VALUE_VARCHAR),
    INDEX IDX_FIELD_VALUE_NUMBER (FIELD_VALUE_NUMBER),
    INDEX IDX_FIELD_VALUE_DATETIME (FIELD_VALUE_DATETIME)
);

CREATE TABLE TBL_CUSTOMER_FIELD (
    CUSTOMER_ID INT NOT NULL,
    FIELD_ID INT NOT NULL,
    FIELD_VALUE_ID INT NOT NULL,
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID, FIELD_ID, FIELD_VALUE_ID)
);
