CREATE TABLE TBL_ORGANIZATION (
    ORGANIZATION_ID INT NOT NULL AUTO_INCREMENT,
    ORGANIZATION_NAME VARCHAR(255),
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ORGANIZATION_ID)
);

CREATE TABLE TBL_CUSTOMER (
    CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
    ORGANIZATION_ID INT NOT NULL,
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID),
    INDEX IDX_ORG_CUSTOMER_ID (ORGANIZATION_ID, CUSTOMER_ID)
);

CREATE TABLE TBL_ORGANIZATION_FIELD (
    ORGANIZATION_ID INT NOT NULL,
    FIELD_ID INT NOT NULL AUTO_INCREMENT,
    FIELD_NAME VARCHAR(255) NOT NULL,
    FIELD_TYPE VARCHAR(255) NOT NULL,
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (FIELD_ID),
    INDEX IDX_ORG_FIELD_ID (ORGANIZATION_ID, FIELD_ID)
);

CREATE TABLE TBL_CUSTOMER_FIELD (
    CUSTOMER_ID INT NOT NULL,
    FIELD_ID INT NOT NULL,
    FIELD_VALUE TEXT,
    REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MDF_DT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID, FIELD_ID)
);
