-- Insert organizations
INSERT INTO TBL_ORGANIZATION (ORGANIZATION_NAME)
VALUES ('Acme Inc.'), ('Blue Sky Inc.');

-- Insert custom fields for Acme Inc.
INSERT INTO TBL_ORGANIZATION_FIELD (ORGANIZATION_ID, FIELD_NAME, FIELD_TYPE)
VALUES
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.'), 'Name', 'TEXT'),
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.'), 'Email', 'EMAIL'),
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.'), 'Phone Number', 'PHONE_NUMBER'),
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.'), 'Date of Birth', 'DATE'),
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.'), 'Gender', 'GENDER');

-- Insert custom fields for Blue Sky Inc.
INSERT INTO TBL_ORGANIZATION_FIELD (ORGANIZATION_ID, FIELD_NAME, FIELD_TYPE)
VALUES
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.'), 'Name', 'TEXT'),
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.'), 'Email', 'EMAIL'),
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.'), 'Phone Number', 'PHONE_NUMBER'),
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.'), 'Instagram Handler', 'TEXT'),
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.'), 'Subscription Level', 'NUMBER');

-- Insert customers for Acme Inc.
INSERT INTO TBL_CUSTOMER (ORGANIZATION_ID)
VALUES
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.'));

-- Insert customers for Blue Sky Inc.
INSERT INTO TBL_CUSTOMER (ORGANIZATION_ID)
VALUES
((SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.'));

-- Insert customer field values for Acme Inc.
INSERT INTO TBL_CUSTOMER_FIELD (CUSTOMER_ID, FIELD_ID, FIELD_VALUE)
VALUES
((SELECT CUSTOMER_ID FROM TBL_CUSTOMER WHERE ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.') LIMIT 1),
 (SELECT FIELD_ID FROM TBL_ORGANIZATION_FIELD WHERE FIELD_NAME = 'Name' AND ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.')),
 'John Doe'),
((SELECT CUSTOMER_ID FROM TBL_CUSTOMER WHERE ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.') LIMIT 1),
 (SELECT FIELD_ID FROM TBL_ORGANIZATION_FIELD WHERE FIELD_NAME = 'Email' AND ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.')),
 'john.doe@acme.com'),
((SELECT CUSTOMER_ID FROM TBL_CUSTOMER WHERE ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.') LIMIT 1),
 (SELECT FIELD_ID FROM TBL_ORGANIZATION_FIELD WHERE FIELD_NAME = 'Phone Number' AND ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.')),
 '123-456-7890'),
((SELECT CUSTOMER_ID FROM TBL_CUSTOMER WHERE ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.') LIMIT 1),
 (SELECT FIELD_ID FROM TBL_ORGANIZATION_FIELD WHERE FIELD_NAME = 'Date of Birth' AND ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.')),
 '1990-01-01'),
((SELECT CUSTOMER_ID FROM TBL_CUSTOMER WHERE ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.') LIMIT 1),
 (SELECT FIELD_ID FROM TBL_ORGANIZATION_FIELD WHERE FIELD_NAME = 'Gender' AND ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Acme Inc.')),
 'Male');

-- Insert customer field values for Blue Sky Inc.
INSERT INTO TBL_CUSTOMER_FIELD (CUSTOMER_ID, FIELD_ID, FIELD_VALUE)
VALUES
((SELECT CUSTOMER_ID FROM TBL_CUSTOMER WHERE ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.') LIMIT 1),
 (SELECT FIELD_ID FROM TBL_ORGANIZATION_FIELD WHERE FIELD_NAME = 'Name' AND ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.')),
 'Alice Johnson'),
((SELECT CUSTOMER_ID FROM TBL_CUSTOMER WHERE ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.') LIMIT 1),
 (SELECT FIELD_ID FROM TBL_ORGANIZATION_FIELD WHERE FIELD_NAME = 'Email' AND ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.')),
 'alice.johnson@bluesky.com'),
((SELECT CUSTOMER_ID FROM TBL_CUSTOMER WHERE ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.') LIMIT 1),
 (SELECT FIELD_ID FROM TBL_ORGANIZATION_FIELD WHERE FIELD_NAME = 'Phone Number' AND ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.')),
 '555-111-2222'),
((SELECT CUSTOMER_ID FROM TBL_CUSTOMER WHERE ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.') LIMIT 1),
 (SELECT FIELD_ID FROM TBL_ORGANIZATION_FIELD WHERE FIELD_NAME = 'Instagram Handler' AND ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.')),
 '@alicejohnson'),
((SELECT CUSTOMER_ID FROM TBL_CUSTOMER WHERE ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.') LIMIT 1),
 (SELECT FIELD_ID FROM TBL_ORGANIZATION_FIELD WHERE FIELD_NAME = 'Subscription Level' AND ORGANIZATION_ID = (SELECT ORGANIZATION_ID FROM TBL_ORGANIZATION WHERE ORGANIZATION_NAME = 'Blue Sky Inc.')),
 '2');
